export const DEFAULT_FORM_VALUES = {
  CLOCK_MODE: 'trueSolar' as const,
  TIMEZONE_OFFSET: '8',
  LONGITUDE: '120.000',
  XIAO_XIAN_RULE: 'yearBranch' as const,
  LIU_NIAN_RULE: 'yearForward' as const,
  DEFAULT_SOLAR_YEAR: '1990',
  DEFAULT_SOLAR_MONTH: '06',
  DEFAULT_SOLAR_DAY: '15',
  DEFAULT_LUNAR_YEAR: '1990',
  DEFAULT_LUNAR_MONTH: '5',
  DEFAULT_LUNAR_DAY: '23',
  DEFAULT_BIRTH_HOUR: '12',
  DEFAULT_BIRTH_MINUTE: '00'
}

export const UI_LABELS = {
  PAGE_TITLE: '紫微斗数命盘',
  PAGE_SUBTITLE: '公历／农历输入，自动排出完整方盘命盘',
  BTN_GENERATE: '排盘',
  BTN_SHARE: '分享海报',
  BTN_AI_LOADING: 'AI 分析中...',
  BTN_AI_RETRY: '重新生成',
  BTN_AI_INITIAL: 'AI 深度解盘',
  STEP_1: '填写出生时间',
  STEP_2: '点击排盘',
  STEP_3: '点击 AI 解读',
  LABEL_PROFILE: '命主名称（可选）',
  LABEL_CALENDAR: '历注输入',
  LABEL_SOLAR_YEAR: '公历年份',
  LABEL_LUNAR_YEAR: '农历年份',
  LABEL_MONTH: '月份',
  LABEL_LUNAR_MONTH: '农历月份',
  LABEL_DAY: '日期',
  LABEL_LUNAR_DAY: '农历日期',
  LABEL_BIRTH_HOUR: '出生时辰',
  LABEL_BIRTH_MINUTE: '出生分钟',
  LABEL_GENDER: '性别',
  LABEL_PROVINCE: '出生省份',
  LABEL_CITY: '出生城市',
  LABEL_LONGITUDE: '出生地经度',
  LABEL_MALE: '男',
  LABEL_FEMALE: '女',
  CALENDAR_SOLAR: '公历输入',
  CALENDAR_LUNAR: '农历输入',
  PLACEHOLDER_PROFILE: '例如：张明远',
  PLACEHOLDER_AI_QUESTION: '输入你的问题...',
  HINT_PROFILE: '用于生成个性化解读',
  HINT_AI_QA_READY: '当前可直接提问，也可以在阅读解读后继续追问',
  HINT_AI_QA_NOT_READY: '完成排盘后即可直接提问，问答会基于当前命盘内容回答',
  HINT_AI_QA_DEVELOPING: '问答功能开发中...',
  HINT_AI_QA_LOADING: 'AI 正在思考...',
  EMPTY_TITLE: '等待排盘',
  EMPTY_DESC: '填写出生信息后点击「排盘」按钮\n将生成完整紫微斗数方盘',
  CHART_TITLE: '图片命盘',
  AI_BADGE: 'AI POWERED',
  AI_TITLE: 'AI 个性化解盘',
  AI_DESC_GENERATED: '已生成',
  AI_DESC_NOT_GENERATED: '基于当前命盘信息生成，未生成',
  AI_DISCLAIMER: '本分析仅供参考娱乐，不代表专业建议。',
  QA_TITLE: '向 AI 命盘问问',
  QA_DESC: '可直接输入问题，或点击查看推荐提问问题',
  COMPASS_TOP: '正南方',
  COMPASS_RIGHT: '正西方',
  COMPASS_BOTTOM: '正北方',
  COMPASS_LEFT: '正东方',
  TIMELINE_DAXIAN: '大限',
  TIMELINE_LIUNIAN: '流年',
  NAV_MING: '命宫',
  NAV_QIANYI: '迁移宫',
  NAV_KE: '科天梁',
  NAV_JIAO: '全交图',
  HINT_TRUE_SOLAR: '已启用真太阳时（经度 + 均时差）校正',
  USER_NAME: '开发者',
  USER_EMAIL: 'developer@local.dev',
  MENU_LOGOUT: '退出登录',
  SUCCESS_GENERATED: '排盘完成。'
}
