/* ===== samples.js — 示例数据 (DDL / 函数 / 存储过程) ===== */
export const DB_LABELS = { oracle: 'Oracle', mysql: 'MySQL', postgresql: 'PostgreSQL' };

/* ===== DDL SAMPLES ===== */
const DDL_SAMPLES = {
oracle: `-- 客户信息主表
CREATE TABLE T_CLIENT_INFO (
    CLIENT_ID      NUMBER(18)       GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CLIENT_NO      VARCHAR2(32)     NOT NULL,
    CLIENT_NAME    NVARCHAR2(200),
    CERT_TYPE      CHAR(2)          DEFAULT '01',
    CERT_NO        VARCHAR2(30),
    BIRTH_DATE     DATE,
    GENDER         CHAR(1),
    PHONE          VARCHAR2(20),
    EMAIL          VARCHAR2(100),
    ADDRESS        VARCHAR2(500),
    BALANCE        NUMBER(18,2)     DEFAULT 0,
    STATUS         VARCHAR2(10)     DEFAULT 'ACTIVE',
    RISK_LEVEL     NUMBER(3),
    REMARK         CLOB,
    PHOTO          BLOB,
    RAW_DATA       RAW(2000),
    IS_VIP         NUMBER(1)        DEFAULT 0,
    CREATE_TIME    TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP,
    CONSTRAINT PK_CLIENT_INFO PRIMARY KEY (CLIENT_ID)
);

COMMENT ON TABLE T_CLIENT_INFO IS '客户基本信息表';
COMMENT ON COLUMN T_CLIENT_INFO.CLIENT_ID IS '客户ID-主键自增';
COMMENT ON COLUMN T_CLIENT_INFO.CLIENT_NO IS '客户编号-唯一业务标识';
COMMENT ON COLUMN T_CLIENT_INFO.CLIENT_NAME IS '客户姓名';
COMMENT ON COLUMN T_CLIENT_INFO.CERT_TYPE IS '证件类型: 01-身份证 02-护照 03-军官证';
COMMENT ON COLUMN T_CLIENT_INFO.CERT_NO IS '证件号码';
COMMENT ON COLUMN T_CLIENT_INFO.BIRTH_DATE IS '出生日期';
COMMENT ON COLUMN T_CLIENT_INFO.BALANCE IS '账户余额';
COMMENT ON COLUMN T_CLIENT_INFO.STATUS IS '状态: ACTIVE-有效 FROZEN-冻结 CLOSED-注销';
COMMENT ON COLUMN T_CLIENT_INFO.REMARK IS '备注-大文本';
COMMENT ON COLUMN T_CLIENT_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_CLIENT_INFO.UPDATE_TIME IS '最后更新时间';

CREATE UNIQUE INDEX IDX_UNI_CLIENT_NO ON T_CLIENT_INFO(CLIENT_NO);
CREATE INDEX IDX_CLIENT_NAME ON T_CLIENT_INFO(CLIENT_NAME);
CREATE INDEX IDX_CLIENT_CERT ON T_CLIENT_INFO(CERT_TYPE, CERT_NO);
CREATE INDEX IDX_CLIENT_STATUS ON T_CLIENT_INFO(STATUS, CREATE_TIME);

-- 交易流水表（按日期范围分区）
CREATE TABLE T_TRADE_RECORD (
    TRADE_ID       NUMBER(18)       NOT NULL,
    CLIENT_NO      VARCHAR2(32)     NOT NULL,
    TRADE_DATE     DATE             NOT NULL,
    TRADE_TYPE     VARCHAR2(10),
    AMOUNT         NUMBER(18,2),
    STATUS         VARCHAR2(10)     DEFAULT 'PENDING',
    CREATE_TIME    TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_TRADE_RECORD PRIMARY KEY (TRADE_ID, TRADE_DATE)
)
PARTITION BY RANGE (TRADE_DATE) (
    PARTITION P_2024Q1 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION P_2024Q2 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD')),
    PARTITION P_2024Q3 VALUES LESS THAN (TO_DATE('2024-10-01', 'YYYY-MM-DD')),
    PARTITION P_2024Q4 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

COMMENT ON TABLE T_TRADE_RECORD IS '交易流水记录表-按季度分区';
COMMENT ON COLUMN T_TRADE_RECORD.TRADE_ID IS '交易流水号';
COMMENT ON COLUMN T_TRADE_RECORD.TRADE_DATE IS '交易日期-分区键';
COMMENT ON COLUMN T_TRADE_RECORD.AMOUNT IS '交易金额';

CREATE INDEX IDX_TRADE_CLIENT ON T_TRADE_RECORD(CLIENT_NO, TRADE_DATE) LOCAL;
CREATE INDEX IDX_TRADE_STATUS ON T_TRADE_RECORD(STATUS);

ALTER TABLE T_TRADE_RECORD ADD CONSTRAINT FK_TRADE_CLIENT FOREIGN KEY (CLIENT_NO) REFERENCES T_CLIENT_INFO(CLIENT_NO) ON DELETE CASCADE;

-- 列表分区示例
CREATE TABLE T_REGION_DATA (
    REGION_ID    NUMBER(10)    NOT NULL,
    REGION_CODE  VARCHAR2(10)  NOT NULL,
    DATA_VALUE   NUMBER(18,2),
    CONSTRAINT PK_REGION_DATA PRIMARY KEY (REGION_ID)
)
PARTITION BY LIST (REGION_CODE) (
    PARTITION P_EAST VALUES ('SH','NJ','HZ'),
    PARTITION P_SOUTH VALUES ('GZ','SZ','XM'),
    PARTITION P_NORTH VALUES ('BJ','TJ','DL'),
    PARTITION P_WEST VALUES ('CD','CQ','XA')
);

COMMENT ON TABLE T_REGION_DATA IS '区域数据表-按地区列表分区';
COMMENT ON COLUMN T_REGION_DATA.REGION_ID IS '区域记录ID';
COMMENT ON COLUMN T_REGION_DATA.REGION_CODE IS '区域编码-分区键';
COMMENT ON COLUMN T_REGION_DATA.DATA_VALUE IS '数据值';

-- HASH分区示例
CREATE TABLE T_LOG_DATA (
    LOG_ID      NUMBER(18)    NOT NULL,
    USER_ID     NUMBER(18)    NOT NULL,
    LOG_MSG     VARCHAR2(500),
    LOG_TIME    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_LOG_DATA PRIMARY KEY (LOG_ID)
)
PARTITION BY HASH (USER_ID) PARTITIONS 8;

COMMENT ON TABLE T_LOG_DATA IS '日志数据表-按用户HASH分区';
COMMENT ON COLUMN T_LOG_DATA.LOG_ID IS '日志ID';
COMMENT ON COLUMN T_LOG_DATA.USER_ID IS '用户ID-分区键';
COMMENT ON COLUMN T_LOG_DATA.LOG_MSG IS '日志内容';`,

mysql: `-- 客户信息主表
CREATE TABLE t_client_info (
    client_id      BIGINT           NOT NULL AUTO_INCREMENT,
    client_no      VARCHAR(32)      NOT NULL,
    client_name    VARCHAR(200)     CHARACTER SET utf8mb4,
    cert_type      CHAR(2)          DEFAULT '01',
    cert_no        VARCHAR(30),
    birth_date     DATETIME,
    gender         CHAR(1),
    phone          VARCHAR(20),
    email          VARCHAR(100),
    balance        DECIMAL(18,2)    DEFAULT 0,
    status         VARCHAR(10)      DEFAULT 'ACTIVE',
    risk_level     INT,
    remark         LONGTEXT,
    photo          LONGBLOB,
    is_vip         TINYINT(1)       DEFAULT 0,
    create_time    TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    update_time    TIMESTAMP(6)     NULL ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (client_id),
    UNIQUE KEY idx_uni_client_no (client_no),
    KEY idx_client_name (client_name),
    KEY idx_client_cert (cert_type, cert_no),
    KEY idx_client_status (status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='客户基本信息表';

-- 交易流水表（按日期范围分区）
CREATE TABLE t_trade_record (
    trade_id       BIGINT           NOT NULL,
    client_no      VARCHAR(32)      NOT NULL,
    trade_date     DATETIME         NOT NULL,
    trade_type     VARCHAR(10),
    amount         DECIMAL(18,2),
    status         VARCHAR(10)      DEFAULT 'PENDING',
    create_time    TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (trade_id, trade_date),
    KEY idx_trade_client (client_no, trade_date),
    KEY idx_trade_status (status),
    CONSTRAINT fk_trade_client FOREIGN KEY (client_no) REFERENCES t_client_info(client_no) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='交易流水记录表-按季度分区'
  PARTITION BY RANGE (TO_DAYS(trade_date)) (
    PARTITION p_2024q1 VALUES LESS THAN (TO_DAYS('2024-04-01')),
    PARTITION p_2024q2 VALUES LESS THAN (TO_DAYS('2024-07-01')),
    PARTITION p_2024q3 VALUES LESS THAN (TO_DAYS('2024-10-01')),
    PARTITION p_2024q4 VALUES LESS THAN (TO_DAYS('2025-01-01')),
    PARTITION p_max VALUES LESS THAN MAXVALUE
);

-- 列表分区示例
CREATE TABLE t_region_data (
    region_id    INT              NOT NULL,
    region_code  VARCHAR(10)      NOT NULL,
    data_value   DECIMAL(18,2),
    PRIMARY KEY (region_id, region_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='区域数据表-按地区列表分区'
  PARTITION BY LIST COLUMNS(region_code) (
    PARTITION p_east VALUES IN ('SH','NJ','HZ'),
    PARTITION p_south VALUES IN ('GZ','SZ','XM'),
    PARTITION p_north VALUES IN ('BJ','TJ','DL'),
    PARTITION p_west VALUES IN ('CD','CQ','XA')
  );

-- HASH分区示例
CREATE TABLE t_log_data (
    log_id       BIGINT           NOT NULL,
    user_id      BIGINT           NOT NULL,
    log_msg      VARCHAR(500),
    log_time     TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (log_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='日志数据表-按用户HASH分区'
  PARTITION BY HASH(user_id) PARTITIONS 8;`,

postgresql: `-- 客户信息主表
CREATE TABLE t_client_info (
    client_id      BIGSERIAL        NOT NULL,
    client_no      VARCHAR(32)      NOT NULL,
    client_name    VARCHAR(200),
    cert_type      CHAR(2)          DEFAULT '01',
    cert_no        VARCHAR(30),
    birth_date     TIMESTAMP,
    gender         CHAR(1),
    phone          VARCHAR(20),
    email          VARCHAR(100),
    balance        NUMERIC(18,2)    DEFAULT 0,
    status         VARCHAR(10)      DEFAULT 'ACTIVE',
    risk_level     INTEGER,
    remark         TEXT,
    photo          BYTEA,
    is_vip         BOOLEAN          DEFAULT FALSE,
    create_time    TIMESTAMP        DEFAULT CLOCK_TIMESTAMP() NOT NULL,
    update_time    TIMESTAMP,
    CONSTRAINT pk_client_info PRIMARY KEY (client_id)
);

COMMENT ON TABLE t_client_info IS '客户基本信息表';
COMMENT ON COLUMN t_client_info.client_id IS '客户ID-主键自增';
COMMENT ON COLUMN t_client_info.client_no IS '客户编号-唯一业务标识';
COMMENT ON COLUMN t_client_info.client_name IS '客户姓名';
COMMENT ON COLUMN t_client_info.cert_type IS '证件类型: 01-身份证 02-护照 03-军官证';
COMMENT ON COLUMN t_client_info.cert_no IS '证件号码';
COMMENT ON COLUMN t_client_info.birth_date IS '出生日期';
COMMENT ON COLUMN t_client_info.balance IS '账户余额';
COMMENT ON COLUMN t_client_info.status IS '状态: ACTIVE-有效 FROZEN-冻结 CLOSED-注销';
COMMENT ON COLUMN t_client_info.remark IS '备注-大文本';
COMMENT ON COLUMN t_client_info.create_time IS '创建时间';
COMMENT ON COLUMN t_client_info.update_time IS '最后更新时间';

CREATE UNIQUE INDEX idx_uni_client_no ON t_client_info(client_no);
CREATE INDEX idx_client_name ON t_client_info(client_name);
CREATE INDEX idx_client_cert ON t_client_info(cert_type, cert_no);
CREATE INDEX idx_client_status ON t_client_info(status, create_time);

-- 交易流水表（按日期范围分区）
CREATE TABLE t_trade_record (
    trade_id       BIGINT           NOT NULL,
    client_no      VARCHAR(32)      NOT NULL,
    trade_date     TIMESTAMP        NOT NULL,
    trade_type     VARCHAR(10),
    amount         NUMERIC(18,2),
    status         VARCHAR(10)      DEFAULT 'PENDING',
    create_time    TIMESTAMP        DEFAULT CLOCK_TIMESTAMP(),
    CONSTRAINT pk_trade_record PRIMARY KEY (trade_id, trade_date)
) PARTITION BY RANGE (trade_date);

CREATE TABLE t_trade_record_2024q1 PARTITION OF t_trade_record
    FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');
CREATE TABLE t_trade_record_2024q2 PARTITION OF t_trade_record
    FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');
CREATE TABLE t_trade_record_2024q3 PARTITION OF t_trade_record
    FOR VALUES FROM ('2024-07-01') TO ('2024-10-01');
CREATE TABLE t_trade_record_2024q4 PARTITION OF t_trade_record
    FOR VALUES FROM ('2024-10-01') TO ('2025-01-01');

COMMENT ON TABLE t_trade_record IS '交易流水记录表-按季度分区';
COMMENT ON COLUMN t_trade_record.trade_id IS '交易流水号';
COMMENT ON COLUMN t_trade_record.trade_date IS '交易日期-分区键';
COMMENT ON COLUMN t_trade_record.amount IS '交易金额';

CREATE INDEX idx_trade_client ON t_trade_record(client_no, trade_date);
CREATE INDEX idx_trade_status ON t_trade_record(status);

ALTER TABLE t_trade_record ADD CONSTRAINT fk_trade_client FOREIGN KEY (client_no) REFERENCES t_client_info(client_no) ON DELETE CASCADE;

-- 列表分区示例
CREATE TABLE t_region_data (
    region_id    INTEGER          NOT NULL,
    region_code  VARCHAR(10)      NOT NULL,
    data_value   NUMERIC(18,2),
    CONSTRAINT pk_region_data PRIMARY KEY (region_id, region_code)
) PARTITION BY LIST (region_code);

CREATE TABLE t_region_data_east PARTITION OF t_region_data
    FOR VALUES IN ('SH','NJ','HZ');
CREATE TABLE t_region_data_south PARTITION OF t_region_data
    FOR VALUES IN ('GZ','SZ','XM');
CREATE TABLE t_region_data_north PARTITION OF t_region_data
    FOR VALUES IN ('BJ','TJ','DL');
CREATE TABLE t_region_data_west PARTITION OF t_region_data
    FOR VALUES IN ('CD','CQ','XA');

COMMENT ON TABLE t_region_data IS '区域数据表-按地区列表分区';
COMMENT ON COLUMN t_region_data.region_id IS '区域记录ID';
COMMENT ON COLUMN t_region_data.region_code IS '区域编码-分区键';
COMMENT ON COLUMN t_region_data.data_value IS '数据值';

-- HASH分区示例
CREATE TABLE t_log_data (
    log_id       BIGINT           NOT NULL,
    user_id      BIGINT           NOT NULL,
    log_msg      VARCHAR(500),
    log_time     TIMESTAMP        DEFAULT CLOCK_TIMESTAMP(),
    CONSTRAINT pk_log_data PRIMARY KEY (log_id, user_id)
) PARTITION BY HASH (user_id);

CREATE TABLE t_log_data_p0 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 0);
CREATE TABLE t_log_data_p1 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 1);
CREATE TABLE t_log_data_p2 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 2);
CREATE TABLE t_log_data_p3 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 3);
CREATE TABLE t_log_data_p4 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 4);
CREATE TABLE t_log_data_p5 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 5);
CREATE TABLE t_log_data_p6 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 6);
CREATE TABLE t_log_data_p7 PARTITION OF t_log_data
    FOR VALUES WITH (modulus 8, remainder 7);

COMMENT ON TABLE t_log_data IS '日志数据表-按用户HASH分区';
COMMENT ON COLUMN t_log_data.log_id IS '日志ID';
COMMENT ON COLUMN t_log_data.user_id IS '用户ID-分区键';
COMMENT ON COLUMN t_log_data.log_msg IS '日志内容';`
};

/* ===== FUNC SAMPLES ===== */
const FUNC_SAMPLES = {
oracle: `-- [1] String ops: SUBSTR, LENGTH, INSTR, REPLACE, LPAD, INITCAP, || concat
-- [2] Date/null: TO_CHAR, TO_DATE, TRUNC(date,'MM'), ADD_MONTHS, SYSDATE, NVL, NVL2, DECODE
-- [3] Exception: NO_DATA_FOUND, WHEN OTHERS, SQLERRM, SQLCODE, DBMS_OUTPUT.PUT_LINE
CREATE OR REPLACE FUNCTION FN_FORMAT_CLIENT_LABEL(
    P_CLIENT_NO  IN VARCHAR2,
    P_AS_OF_DATE IN VARCHAR2 DEFAULT NULL
) RETURN VARCHAR2
IS
    V_NAME     VARCHAR2(200);
    V_STATUS   VARCHAR2(20);
    V_JOINED   DATE;
    V_LABEL    VARCHAR2(500);
    V_DT       DATE;
    V_POS      NUMBER;
BEGIN
    -- TO_DATE, NVL, SYSDATE
    V_DT := NVL(TO_DATE(P_AS_OF_DATE, 'YYYY-MM-DD'), SYSDATE);
    -- SELECT INTO
    SELECT CLIENT_NAME, STATUS, JOIN_DATE
      INTO V_NAME, V_STATUS, V_JOINED
      FROM T_CLIENT_INFO
     WHERE CLIENT_NO = P_CLIENT_NO;
    -- INITCAP, SUBSTR, LENGTH, INSTR, REPLACE
    V_NAME := INITCAP(REPLACE(V_NAME, '_', ' '));
    V_POS  := INSTR(V_NAME, ' ');
    IF V_POS > 0 THEN
        V_NAME := SUBSTR(V_NAME, 1, V_POS) || LPAD(SUBSTR(V_NAME, V_POS + 1, 1), 1) || '.';
    END IF;
    -- DECODE, NVL2, TO_CHAR, TRUNC, ADD_MONTHS, || concat
    V_LABEL := V_NAME
        || ' [' || DECODE(V_STATUS, 'ACTIVE', 'A', 'FROZEN', 'F', 'X') || ']'
        || NVL2(V_JOINED, ' since ' || TO_CHAR(TRUNC(V_JOINED, 'MM'), 'YYYY-MM'), ' new')
        || ' months=' || FLOOR(MONTHS_BETWEEN(V_DT, NVL(V_JOINED, ADD_MONTHS(V_DT, -1))));
    RETURN V_LABEL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Client not found: ' || P_CLIENT_NO);
        RETURN NULL;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('FN_FORMAT_CLIENT_LABEL err ' || SQLCODE || ': ' || SQLERRM);
        RETURN NULL;
END FN_FORMAT_CLIENT_LABEL;
/

-- [4] WHILE loop, basic computation
-- [5] EXECUTE IMMEDIATE (dynamic SQL in function)
-- [6] RAISE_APPLICATION_ERROR
CREATE OR REPLACE FUNCTION FN_COUNT_DYNAMIC(
    P_TABLE_NAME IN VARCHAR2,
    P_MAX_WAIT   IN NUMBER DEFAULT 5
) RETURN NUMBER
IS
    V_SQL   VARCHAR2(500);
    V_COUNT NUMBER;
    V_TRIES NUMBER := 0;
BEGIN
    IF P_TABLE_NAME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Table name must not be null');
    END IF;
    -- WHILE loop with retry
    WHILE V_TRIES < P_MAX_WAIT LOOP
        BEGIN
            V_SQL := 'SELECT COUNT(*) FROM ' || P_TABLE_NAME;
            EXECUTE IMMEDIATE V_SQL INTO V_COUNT;
            RETURN V_COUNT;
        EXCEPTION
            WHEN OTHERS THEN
                V_TRIES := V_TRIES + 1;
        END;
    END LOOP;
    RAISE_APPLICATION_ERROR(-20002, 'Failed after ' || P_MAX_WAIT || ' attempts');
END FN_COUNT_DYNAMIC;
/

-- [7] DBMS_RANDOM.VALUE, LENGTHB
-- [8] Sequence .NEXTVAL usage
CREATE OR REPLACE FUNCTION FN_GENERATE_TOKEN(
    P_PREFIX IN VARCHAR2 DEFAULT 'TKN'
) RETURN VARCHAR2
IS
    V_SEQ   NUMBER;
    V_RAND  NUMBER;
    V_TOKEN VARCHAR2(100);
BEGIN
    -- Sequence .NEXTVAL
    SELECT SEQ_TOKEN.NEXTVAL INTO V_SEQ FROM DUAL;
    -- DBMS_RANDOM.VALUE
    V_RAND := TRUNC(DBMS_RANDOM.VALUE(1000, 9999));
    V_TOKEN := P_PREFIX || '-' || LPAD(TO_CHAR(V_SEQ), 8, '0') || '-' || TO_CHAR(V_RAND);
    -- LENGTHB (byte length check)
    IF LENGTHB(V_TOKEN) > 50 THEN
        V_TOKEN := SUBSTR(V_TOKEN, 1, 50);
    END IF;
    RETURN V_TOKEN;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('FN_GENERATE_TOKEN error: ' || SQLERRM);
        RETURN NULL;
END FN_GENERATE_TOKEN;
/`,

mysql: `-- [1] SUBSTRING, CHAR_LENGTH, INSTR, REPLACE, LPAD, CONCAT
-- [2] DATE_FORMAT, STR_TO_DATE, NOW(), IFNULL, IF(cond,a,b)
-- [3] DECLARE variables, SET variable = expr
DELIMITER $$
CREATE FUNCTION fn_format_client_label(
    p_client_no  VARCHAR(32),
    p_as_of_date VARCHAR(10)
) RETURNS VARCHAR(500)
READS SQL DATA
BEGIN
    DECLARE v_name   VARCHAR(200);
    DECLARE v_status VARCHAR(20);
    DECLARE v_joined DATE;
    DECLARE v_label  VARCHAR(500);
    DECLARE v_dt     DATE;
    DECLARE v_pos    INT;
    -- STR_TO_DATE, IFNULL, NOW()
    SET v_dt = IFNULL(STR_TO_DATE(p_as_of_date, '%Y-%m-%d'), NOW());
    SELECT client_name, status, join_date
      INTO v_name, v_status, v_joined
      FROM t_client_info
     WHERE client_no = p_client_no
     LIMIT 1;
    -- REPLACE, INSTR, SUBSTRING, LPAD, CHAR_LENGTH
    SET v_name = REPLACE(v_name, '_', ' ');
    SET v_pos  = INSTR(v_name, ' ');
    IF v_pos > 0 THEN
        SET v_name = CONCAT(SUBSTRING(v_name, 1, v_pos), LPAD(SUBSTRING(v_name, v_pos + 1, 1), 1), '.');
    END IF;
    -- IF(cond,a,b), CONCAT, DATE_FORMAT
    SET v_label = CONCAT(
        v_name,
        ' [', IF(v_status = 'ACTIVE', 'A', IF(v_status = 'FROZEN', 'F', 'X')), ']',
        IF(v_joined IS NOT NULL,
           CONCAT(' since ', DATE_FORMAT(v_joined, '%Y-%m')),
           ' new'),
        ' months=', CAST(TIMESTAMPDIFF(MONTH, IFNULL(v_joined, DATE_SUB(v_dt, INTERVAL 1 MONTH)), v_dt) AS SIGNED INTEGER)
    );
    RETURN v_label;
END$$
DELIMITER ;

-- [4] WHILE...DO...END WHILE
-- [5] CAST(... AS SIGNED INTEGER)
-- [6] SIGNAL SQLSTATE
DELIMITER $$
CREATE FUNCTION fn_count_dynamic(
    p_table_name VARCHAR(128),
    p_max_wait   INT
) RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_count INT DEFAULT 0;
    DECLARE v_tries INT DEFAULT 0;
    IF p_table_name IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Table name must not be null';
    END IF;
    -- WHILE loop with retry
    WHILE v_tries < CAST(p_max_wait AS SIGNED INTEGER) DO
        SET @_dyn_sql = CONCAT('SELECT COUNT(*) INTO @_dyn_count FROM ', p_table_name);
        PREPARE _dyn_stmt FROM @_dyn_sql;
        EXECUTE _dyn_stmt;
        DEALLOCATE PREPARE _dyn_stmt;
        SET v_count = @_dyn_count;
        IF v_count >= 0 THEN
            RETURN v_count;
        END IF;
        SET v_tries = v_tries + 1;
    END WHILE;
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Failed after max attempts';
END$$
DELIMITER ;`,

postgresql: `-- [1] SUBSTR, LENGTH, strpos, replace, lpad, initcap, || concat
-- [2] to_char, to_date, date_trunc, COALESCE, CURRENT_DATE, CURRENT_TIMESTAMP
-- [3] EXCEPTION WHEN NO_DATA_FOUND / WHEN OTHERS, SQLERRM, RAISE NOTICE
CREATE OR REPLACE FUNCTION fn_format_client_label(
    p_client_no  VARCHAR,
    p_as_of_date VARCHAR DEFAULT NULL
) RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE
    v_name   VARCHAR(200);
    v_status VARCHAR(20);
    v_joined DATE;
    v_label  VARCHAR(500);
    v_dt     DATE;
    v_pos    INTEGER;
BEGIN
    -- to_date, COALESCE, CURRENT_DATE
    v_dt := COALESCE(to_date(p_as_of_date, 'YYYY-MM-DD'), CURRENT_DATE);
    -- SELECT INTO
    SELECT client_name, status, join_date
      INTO v_name, v_status, v_joined
      FROM t_client_info
     WHERE client_no = p_client_no;
    -- initcap, replace, strpos, SUBSTR, lpad, LENGTH
    v_name := initcap(replace(v_name, '_', ' '));
    v_pos  := strpos(v_name, ' ');
    IF v_pos > 0 THEN
        v_name := SUBSTR(v_name, 1, v_pos) || lpad(SUBSTR(v_name, v_pos + 1, 1), 1) || '.';
    END IF;
    -- to_char, date_trunc, || concat
    v_label := v_name
        || ' [' || CASE v_status WHEN 'ACTIVE' THEN 'A' WHEN 'FROZEN' THEN 'F' ELSE 'X' END || ']'
        || COALESCE(' since ' || to_char(date_trunc('month', v_joined), 'YYYY-MM'), ' new')
        || ' len=' || LENGTH(v_name);
    RETURN v_label;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE NOTICE 'Client not found: %', p_client_no;
        RETURN NULL;
    WHEN OTHERS THEN
        RAISE NOTICE 'fn_format_client_label err: %', SQLERRM;
        RETURN NULL;
END;
$$;

-- [4] WHILE loop, FOR loop (numeric)
-- [5] EXECUTE dynamic SQL
-- [6] RAISE EXCEPTION, random()
CREATE OR REPLACE FUNCTION fn_count_dynamic(
    p_table_name VARCHAR,
    p_max_wait   INTEGER DEFAULT 5
) RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_count  INTEGER;
    v_tries  INTEGER := 0;
BEGIN
    IF p_table_name IS NULL THEN
        RAISE EXCEPTION 'Table name must not be null' USING ERRCODE = 'P0001';
    END IF;
    -- WHILE loop with retry
    WHILE v_tries < p_max_wait LOOP
        BEGIN
            EXECUTE 'SELECT COUNT(*) FROM ' || p_table_name INTO v_count;
            RETURN v_count;
        EXCEPTION
            WHEN OTHERS THEN
                v_tries := v_tries + 1;
        END;
    END LOOP;
    RAISE EXCEPTION 'Failed after % attempts', p_max_wait;
END;
$$;

-- random(), FOR numeric loop, CURRENT_TIMESTAMP
CREATE OR REPLACE FUNCTION fn_generate_token(
    p_prefix VARCHAR DEFAULT 'TKN'
) RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE
    v_token VARCHAR(100);
    v_rand  INTEGER;
BEGIN
    v_token := p_prefix;
    -- FOR numeric loop
    FOR i IN 1..3 LOOP
        -- random()
        v_rand := trunc(random() * 9000 + 1000);
        v_token := v_token || '-' || lpad(v_rand::TEXT, 4, '0');
    END LOOP;
    v_token := v_token || '-' || to_char(CURRENT_TIMESTAMP, 'HH24MISS');
    RETURN v_token;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'fn_generate_token error: %', SQLERRM;
        RETURN NULL;
END;
$$;`
};

/* ===== PROC SAMPLES ===== */
const PROC_SAMPLES = {
oracle: `-- [1] CURSOR, OPEN/FETCH/CLOSE, %NOTFOUND, %ISOPEN, %ROWTYPE
-- [2] FOR r IN (SELECT...) LOOP (query FOR), || concat in output
-- [3] SQL%ROWCOUNT, SELECT...INTO, COMMIT/ROLLBACK
-- [10] Full EXCEPTION: NO_DATA_FOUND, WHEN OTHERS, SQLERRM, SQLCODE,
--      DBMS_OUTPUT.PUT_LINE, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, RAISE
CREATE OR REPLACE PROCEDURE SP_FREEZE_LOW_BALANCE(
    P_THRESHOLD IN  NUMBER,
    P_COUNT     OUT NUMBER
)
IS
    CURSOR C_CLIENTS IS
        SELECT CLIENT_NO, CLIENT_NAME, BALANCE
          FROM T_CLIENT_INFO
         WHERE STATUS = 'ACTIVE'
           AND BALANCE < P_THRESHOLD;
    V_REC C_CLIENTS%ROWTYPE;
    V_MSG VARCHAR2(500);
BEGIN
    P_COUNT := 0;
    OPEN C_CLIENTS;
    LOOP
        FETCH C_CLIENTS INTO V_REC;
        EXIT WHEN C_CLIENTS%NOTFOUND;
        -- SQL%ROWCOUNT after UPDATE
        UPDATE T_CLIENT_INFO
           SET STATUS = 'FROZEN', UPDATE_TIME = SYSTIMESTAMP
         WHERE CLIENT_NO = V_REC.CLIENT_NO;
        P_COUNT := P_COUNT + SQL%ROWCOUNT;
    END LOOP;
    CLOSE C_CLIENTS;
    COMMIT;
    -- || concatenation in output
    DBMS_OUTPUT.PUT_LINE('Frozen ' || P_COUNT || ' clients below ' || P_THRESHOLD);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No data found during freeze');
        IF C_CLIENTS%ISOPEN THEN CLOSE C_CLIENTS; END IF;
        ROLLBACK;
    WHEN OTHERS THEN
        IF C_CLIENTS%ISOPEN THEN CLOSE C_CLIENTS; END IF;
        ROLLBACK;
        P_COUNT := -1;
        V_MSG := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        DBMS_OUTPUT.PUT_LINE('SP_FREEZE err ' || SQLCODE || ': ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Backtrace: ' || V_MSG);
        RAISE;
END SP_FREEZE_LOW_BALANCE;
/

-- [4] MERGE INTO...USING...ON...WHEN MATCHED/NOT MATCHED
-- [5] EXECUTE IMMEDIATE with USING and INTO
-- [7] FOR i IN 1..N LOOP (numeric FOR)
CREATE OR REPLACE PROCEDURE SP_SYNC_CLIENT_STATS(
    P_BATCH_SIZE IN  NUMBER DEFAULT 100,
    P_UPDATED    OUT NUMBER
)
IS
    V_SQL   VARCHAR2(500);
    V_CNT   NUMBER;
BEGIN
    P_UPDATED := 0;
    -- MERGE INTO
    MERGE INTO T_CLIENT_STATS S
    USING (
        SELECT CLIENT_NO, COUNT(*) AS TRADE_CNT, SUM(AMOUNT) AS TOTAL_AMT
          FROM T_TRADE_RECORD
         GROUP BY CLIENT_NO
    ) T
    ON (S.CLIENT_NO = T.CLIENT_NO)
    WHEN MATCHED THEN
        UPDATE SET S.TRADE_COUNT = T.TRADE_CNT, S.TOTAL_AMOUNT = T.TOTAL_AMT, S.UPDATE_TIME = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (CLIENT_NO, TRADE_COUNT, TOTAL_AMOUNT, UPDATE_TIME)
        VALUES (T.CLIENT_NO, T.TRADE_CNT, T.TOTAL_AMT, SYSTIMESTAMP);
    P_UPDATED := SQL%ROWCOUNT;
    -- EXECUTE IMMEDIATE with USING and INTO
    V_SQL := 'SELECT COUNT(*) FROM T_CLIENT_STATS WHERE TRADE_COUNT > :min_trades';
    EXECUTE IMMEDIATE V_SQL INTO V_CNT USING 10;
    -- FOR i IN 1..N numeric loop for batch logging
    FOR I IN 1..LEAST(P_UPDATED, 3) LOOP
        DBMS_OUTPUT.PUT_LINE('Batch ' || I || ' of sync complete');
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_UPDATED := -1;
        DBMS_OUTPUT.PUT_LINE('SP_SYNC err ' || SQLCODE || ': ' || SQLERRM);
        RAISE;
END SP_SYNC_CLIENT_STATS;
/

-- [6] FOR r IN (SELECT...) LOOP (query FOR)
-- [8] SELECT...INTO variable
-- [9] Sequence .NEXTVAL, NVL
CREATE OR REPLACE PROCEDURE SP_ARCHIVE_TRADES(
    P_DAYS_OLD IN  NUMBER,
    P_ARCHIVED OUT NUMBER
)
IS
    V_CUTOFF DATE;
BEGIN
    P_ARCHIVED := 0;
    V_CUTOFF := TRUNC(SYSDATE) - P_DAYS_OLD;
    -- FOR r IN (SELECT...) query loop
    FOR REC IN (
        SELECT TRADE_ID, CLIENT_NO, TRADE_DATE, AMOUNT
          FROM T_TRADE_RECORD
         WHERE TRADE_DATE < V_CUTOFF
    ) LOOP
        INSERT INTO T_TRADE_HISTORY (HIST_ID, TRADE_ID, CLIENT_NO, TRADE_DATE, AMOUNT, ARCHIVE_TIME)
        VALUES (SEQ_HIST.NEXTVAL, REC.TRADE_ID, REC.CLIENT_NO, REC.TRADE_DATE, NVL(REC.AMOUNT, 0), SYSTIMESTAMP);
        P_ARCHIVED := P_ARCHIVED + 1;
    END LOOP;
    DELETE FROM T_TRADE_RECORD WHERE TRADE_DATE < V_CUTOFF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Archived ' || P_ARCHIVED || ' trades older than ' || P_DAYS_OLD || ' days');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_ARCHIVED := -1;
        DBMS_OUTPUT.PUT_LINE('SP_ARCHIVE err: ' || SQLERRM);
END SP_ARCHIVE_TRADES;
/`,

mysql: `-- [1] DECLARE cursor, OPEN/FETCH/CLOSE, CONTINUE HANDLER FOR NOT FOUND
-- [6] CONCAT for concatenation, SELECT for debug output
-- [7] START TRANSACTION/COMMIT/ROLLBACK
-- [8] Full DECLARE EXIT HANDLER FOR SQLEXCEPTION with GET DIAGNOSTICS, RESIGNAL
CREATE PROCEDURE sp_freeze_low_balance(
    IN  p_threshold DECIMAL(18,2),
    OUT p_count     INT
)
BEGIN
    DECLARE v_client_no VARCHAR(32);
    DECLARE v_done INT DEFAULT 0;
    DECLARE v_err_msg VARCHAR(500);
    DECLARE v_err_code INT;
    -- [1] CURSOR + HANDLER FOR NOT FOUND
    DECLARE c_clients CURSOR FOR
        SELECT client_no FROM t_client_info
         WHERE status = 'ACTIVE' AND balance < p_threshold;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_done = 1;
    -- [8] EXIT HANDLER with GET DIAGNOSTICS + RESIGNAL
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            v_err_code = MYSQL_ERRNO, v_err_msg = MESSAGE_TEXT;
        ROLLBACK;
        SET p_count = -1;
        SELECT CONCAT('sp_freeze err ', v_err_code, ': ', v_err_msg) AS err_info;
        RESIGNAL;
    END;

    SET p_count = 0;
    START TRANSACTION;
    OPEN c_clients;
    read_loop: LOOP
        FETCH c_clients INTO v_client_no;
        IF v_done THEN LEAVE read_loop; END IF;
        UPDATE t_client_info
           SET status = 'FROZEN', update_time = CURRENT_TIMESTAMP(6)
         WHERE client_no = v_client_no;
        -- [5] SET variable = ROW_COUNT()
        SET p_count = p_count + ROW_COUNT();
    END LOOP;
    CLOSE c_clients;
    COMMIT;
    -- [6] CONCAT + SELECT for debug
    SELECT CONCAT('Frozen ', p_count, ' clients below ', p_threshold) AS msg;
END;

-- [2] WHILE...DO (replacing FOR loops)
-- [3] INSERT...ON DUPLICATE KEY UPDATE (replacing MERGE)
-- [9] SIGNAL SQLSTATE '45000'
-- [10] ELSEIF
CREATE PROCEDURE sp_sync_client_stats(
    IN  p_batch_size INT,
    OUT p_updated    INT
)
BEGIN
    DECLARE v_offset INT DEFAULT 0;
    DECLARE v_batch  INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_updated = -1;
    END;

    SET p_updated = 0;
    IF p_batch_size <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Batch size must be positive';
    ELSEIF p_batch_size > 10000 THEN
        SET p_batch_size = 10000;
    END IF;
    START TRANSACTION;
    -- [3] INSERT...ON DUPLICATE KEY UPDATE (MERGE equivalent)
    INSERT INTO t_client_stats (client_no, trade_count, total_amount, update_time)
    SELECT client_no, COUNT(*), SUM(amount), CURRENT_TIMESTAMP(6)
      FROM t_trade_record
     GROUP BY client_no
    ON DUPLICATE KEY UPDATE
        trade_count  = VALUES(trade_count),
        total_amount = VALUES(total_amount),
        update_time  = CURRENT_TIMESTAMP(6);
    SET p_updated = ROW_COUNT();
    -- [2] WHILE loop (replacing numeric FOR)
    SET v_offset = 1;
    WHILE v_offset <= LEAST(p_updated, 3) DO
        SELECT CONCAT('Batch ', v_offset, ' of sync complete') AS msg;
        SET v_offset = v_offset + 1;
    END WHILE;
    COMMIT;
END;

-- [4] PREPARE/EXECUTE/DEALLOCATE PREPARE (dynamic SQL)
-- [5] SELECT...INTO variable, SET variable = ROW_COUNT()
CREATE PROCEDURE sp_archive_trades(
    IN  p_days_old   INT,
    IN  p_batch_size INT,
    OUT p_archived   INT
)
BEGIN
    DECLARE v_cutoff DATE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_archived = -1;
    END;

    SET p_archived = 0;
    SET v_cutoff = DATE_SUB(NOW(), INTERVAL p_days_old DAY);
    START TRANSACTION;
    -- Archive using INSERT...SELECT
    INSERT IGNORE INTO t_trade_history (trade_id, client_no, trade_date, amount, archive_time)
    SELECT trade_id, client_no, trade_date, IFNULL(amount, 0), CURRENT_TIMESTAMP(6)
      FROM t_trade_record
     WHERE trade_date < v_cutoff
     LIMIT p_batch_size;
    SET p_archived = ROW_COUNT();
    -- [4] Dynamic SQL with PREPARE/EXECUTE
    SET @_dyn_sql = CONCAT('DELETE FROM t_trade_record WHERE trade_date < ''',
                           DATE_FORMAT(v_cutoff, '%Y-%m-%d'), ''' LIMIT ', p_batch_size);
    PREPARE _dyn_stmt FROM @_dyn_sql;
    EXECUTE _dyn_stmt;
    DEALLOCATE PREPARE _dyn_stmt;
    COMMIT;
    SELECT CONCAT('Archived ', p_archived, ' trades older than ', p_days_old, ' days') AS msg;
END;`,

postgresql: `-- [1] Explicit cursor with FOUND/NOT FOUND
-- [6] || concatenation, RAISE NOTICE
-- [7] COMMIT/ROLLBACK (in procedure)
-- [8] Full EXCEPTION: NO_DATA_FOUND, WHEN OTHERS, SQLERRM, SQLSTATE,
--     RAISE NOTICE, PG_EXCEPTION_CONTEXT, RAISE
CREATE OR REPLACE PROCEDURE sp_freeze_low_balance(
    IN  p_threshold NUMERIC,
    OUT p_count     INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_rec      RECORD;
    v_ctx      TEXT;
    c_clients CURSOR FOR
        SELECT client_no, client_name, balance
          FROM t_client_info
         WHERE status = 'ACTIVE'
           AND balance < p_threshold;
BEGIN
    p_count := 0;
    OPEN c_clients;
    LOOP
        FETCH c_clients INTO v_rec;
        EXIT WHEN NOT FOUND;
        UPDATE t_client_info
           SET status = 'FROZEN', update_time = CLOCK_TIMESTAMP()
         WHERE client_no = v_rec.client_no;
        p_count := p_count + 1;
    END LOOP;
    CLOSE c_clients;
    COMMIT;
    -- || concatenation, RAISE NOTICE
    RAISE NOTICE 'Frozen % clients below %', p_count, p_threshold;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE NOTICE 'No data found during freeze';
        ROLLBACK;
    WHEN OTHERS THEN
        ROLLBACK;
        p_count := -1;
        GET STACKED DIAGNOSTICS v_ctx = PG_EXCEPTION_CONTEXT;
        RAISE NOTICE 'sp_freeze err SQLSTATE=% : %', SQLSTATE, SQLERRM;
        RAISE NOTICE 'Context: %', v_ctx;
        RAISE;
END;
$$;

-- [2] FOR i IN 1..N LOOP, FOR r IN SELECT...LOOP
-- [3] MERGE INTO (PG 15+)
-- [5] SELECT...INTO variable, GET DIAGNOSTICS v_cnt = ROW_COUNT
CREATE OR REPLACE PROCEDURE sp_sync_client_stats(
    IN  p_batch_size INTEGER DEFAULT 100,
    OUT p_updated    INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_cnt INTEGER;
    rec   RECORD;
BEGIN
    p_updated := 0;
    -- [3] MERGE INTO (PG 15+)
    MERGE INTO t_client_stats S
    USING (
        SELECT client_no, COUNT(*) AS trade_cnt, SUM(amount) AS total_amt
          FROM t_trade_record
         GROUP BY client_no
    ) T
    ON S.client_no = T.client_no
    WHEN MATCHED THEN
        UPDATE SET trade_count = T.trade_cnt, total_amount = T.total_amt, update_time = CLOCK_TIMESTAMP()
    WHEN NOT MATCHED THEN
        INSERT (client_no, trade_count, total_amount, update_time)
        VALUES (T.client_no, T.trade_cnt, T.total_amt, CLOCK_TIMESTAMP());
    -- [5] GET DIAGNOSTICS
    GET DIAGNOSTICS p_updated = ROW_COUNT;
    -- [2] FOR i IN 1..N numeric loop
    FOR i IN 1..LEAST(p_updated, 3) LOOP
        RAISE NOTICE 'Batch % of sync complete', i;
    END LOOP;
    -- [2] FOR r IN SELECT...LOOP
    FOR rec IN SELECT client_no, trade_count FROM t_client_stats WHERE trade_count > 100 LOOP
        RAISE NOTICE 'High-volume client: %', rec.client_no;
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_updated := -1;
        RAISE NOTICE 'sp_sync err: % %', SQLSTATE, SQLERRM;
        RAISE;
END;
$$;

-- [4] EXECUTE dynamic SQL
-- [5] SELECT...INTO
-- Cursor FOR loop shorthand
CREATE OR REPLACE PROCEDURE sp_archive_trades(
    IN  p_days_old   INTEGER,
    IN  p_batch_size INTEGER DEFAULT 1000,
    OUT p_archived   INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_cutoff DATE;
    rec      RECORD;
BEGIN
    p_archived := 0;
    v_cutoff := CURRENT_DATE - p_days_old;
    -- Cursor FOR loop (implicit open/fetch/close)
    FOR rec IN
        SELECT trade_id, client_no, trade_date, COALESCE(amount, 0) AS amount
          FROM t_trade_record
         WHERE trade_date < v_cutoff
         LIMIT p_batch_size
    LOOP
        INSERT INTO t_trade_history (trade_id, client_no, trade_date, amount, archive_time)
        VALUES (rec.trade_id, rec.client_no, rec.trade_date, rec.amount, CLOCK_TIMESTAMP());
        p_archived := p_archived + 1;
    END LOOP;
    -- [4] EXECUTE dynamic SQL
    EXECUTE 'DELETE FROM t_trade_record WHERE trade_date < $1' USING v_cutoff;
    COMMIT;
    RAISE NOTICE 'Archived % trades older than % days', p_archived, p_days_old;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_archived := -1;
        RAISE NOTICE 'sp_archive err: %', SQLERRM;
END;
$$;`
}
