-- 目标数据库: Oracle 19c+ (sqlplus / SQL Developer 执行)
-- ============================================================
-- 自动生成: MySQL → Oracle
-- 表数量: 2, 视图: 2
-- 生成时间: 2026-04-06 14:02:11
-- 请检查类型映射和分区语法是否符合目标库版本要求
-- ============================================================

-- 产品信息表
CREATE TABLE T_PRODUCT (
    PRODUCT_ID         NUMBER(18)           GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    SKU                VARCHAR2(64)         NOT NULL,
    NAME               VARCHAR2(200)       ,
    CATEGORY           CHAR(4)              DEFAULT 'MISC',
    PRICE              NUMBER(12,2)         DEFAULT 0,
    STOCK              NUMBER(10)           DEFAULT 0,
    IS_ON_SALE         NUMBER(1)            DEFAULT 1,
    DESCRIPTION        CLOB                ,
    IMAGE              BLOB                ,
    CREATED_AT         TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP           ,
    CONSTRAINT PK_T_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

COMMENT ON TABLE T_PRODUCT IS '产品信息表';

CREATE UNIQUE INDEX IDX_SKU ON T_PRODUCT(SKU);
CREATE INDEX IDX_CATEGORY ON T_PRODUCT(CATEGORY, PRICE);

-- 产品评价表
CREATE TABLE T_REVIEW (
    REVIEW_ID          NUMBER(18)           GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    PRODUCT_ID         NUMBER(18)           NOT NULL,
    RATING             NUMBER(3)            DEFAULT 5,
    CONTENT            CLOB                ,
    CREATED_AT         DATE                 DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_REVIEW PRIMARY KEY (REVIEW_ID)
);

COMMENT ON TABLE T_REVIEW IS '产品评价表';

ALTER TABLE T_REVIEW ADD CONSTRAINT FK_REVIEW_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID) ON DELETE CASCADE;

CREATE OR REPLACE VIEW V_PRODUCT_STATS AS
SELECT p.product_id, p.sku, p.name,
       NVL(p.price, 0) AS price,
       NVL(AVG(r.rating), 0) AS avg_rating,
       COUNT(r.review_id) AS review_count,
       TO_CHAR(p.created_at, 'YYYY-MM-DD') AS listed_date
  FROM t_product p
  LEFT JOIN t_review r ON p.product_id = r.product_id
 GROUP BY p.product_id, p.sku, p.name, p.price, p.created_at
;

CREATE OR REPLACE VIEW V_ON_SALE AS
SELECT product_id, sku, name, price FROM t_product WHERE is_on_sale = 1
WITH CHECK OPTION
;