-- 目标数据库: Oracle 19c+ (sqlplus / SQL Developer 执行)
-- ============================================================
-- 自动生成: PostgreSQL → Oracle
-- 表数量: 2, 视图: 2
-- 生成时间: 2026-04-06 14:02:11
-- 请检查类型映射和分区语法是否符合目标库版本要求
-- ============================================================

-- 项目管理表
CREATE TABLE T_PROJECT (
    PROJECT_ID         NUMBER(18)           GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    PROJECT_CODE       VARCHAR2(30)         NOT NULL,
    TITLE              VARCHAR2(200)       ,
    BUDGET             NUMBER(15,2)         DEFAULT 0,
    IS_ACTIVE          NUMBER(1)            DEFAULT 1,
    START_DATE         TIMESTAMP           ,
    DESCRIPTION        CLOB                ,
    ATTACHMENT         BLOB                ,
    CREATED_AT         TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID)
);

COMMENT ON TABLE T_PROJECT IS '项目管理表';
COMMENT ON COLUMN T_PROJECT.BUDGET IS '项目预算';
COMMENT ON COLUMN T_PROJECT.IS_ACTIVE IS '是否有效';

CREATE UNIQUE INDEX IDX_PROJECT_CODE ON T_PROJECT(PROJECT_CODE);
CREATE INDEX IDX_PROJECT_ACTIVE ON T_PROJECT(IS_ACTIVE, START_DATE);

-- 任务表
CREATE TABLE T_TASK (
    TASK_ID            NUMBER(10)           GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    PROJECT_ID         NUMBER(18)           NOT NULL,
    TASK_NAME          VARCHAR2(100)       ,
    STATUS             VARCHAR2(20)         DEFAULT 'OPEN',
    CONSTRAINT PK_TASK PRIMARY KEY (TASK_ID)
);

COMMENT ON TABLE T_TASK IS '任务表';

ALTER TABLE T_TASK ADD CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES T_PROJECT(PROJECT_ID) ON DELETE CASCADE;

-- 项目概览视图
CREATE OR REPLACE VIEW V_PROJECT_OVERVIEW AS
SELECT p.project_id, p.project_code, p.title,
       NVL(p.budget, 0) AS budget,
       CASE WHEN p.is_active THEN '有效' ELSE '无效' END AS status,
       COUNT(t.task_id) AS task_count,
       TO_CHAR(p.created_at, 'YYYY-MM-DD') AS created
  FROM t_project p
  LEFT JOIN t_task t ON p.project_id = t.project_id
 GROUP BY p.project_id, p.project_code, p.title, p.budget, p.is_active, p.created_at
;

COMMENT ON TABLE V_PROJECT_OVERVIEW IS '项目概览视图';

-- 活跃项目视图
CREATE OR REPLACE VIEW V_ACTIVE_PROJECTS AS
SELECT project_id, project_code, title, budget
  FROM t_project WHERE is_active = TRUE
WITH CHECK OPTION
;

COMMENT ON TABLE V_ACTIVE_PROJECTS IS '活跃项目视图';